from brain.prompts import (
    EXTRACTION_SYSTEM_PROMPT,
    ENRICHISSEMENT_SYSTEM_PROMPT,
    RESUME_VOCAL_PROMPT,
)

__all__ = [
    "EXTRACTION_SYSTEM_PROMPT",
    "ENRICHISSEMENT_SYSTEM_PROMPT",
    "RESUME_VOCAL_PROMPT",
]
